export const DEFAULT_PRESETS = {
    "Neón Synthwave": {
        "text-type": "static",
        "input-text": "SYNTHWAVE",
        "font-family": "Bebas Neue",
        "font-size": "120",
        "font-weight": "800",
        "text-scale": "1.2",
        "color-type": "gradient",
        "gradient-color-1": "#ff007f",
        "gradient-color-2": "#00ffff",
        "gradient-angle": "45",
        "stroke-color": "#000000",
        "stroke-width": "3",
        "enable-shadow": "false",
        "enable-neon": "true",
        "neon-color": "#ff007f",
        "neon-blur": "30",
        "stagger-mode": "char",
        "stagger-speed": "0.08",
        "anim-preset": "blur-reveal",
        "anim-duration": "1.2",
        "anim-delay": "0.2",
        "anim-ease": "power4.out",
        "loop-preset": "float",
        "loop-cycle-duration": "2.0",
        "loop-intensity": "1.5",
        "hold-duration": "4",
        "outro-preset": "fade",
        "outro-duration": "0.8",
        "outro-ease": "power2.in"
    },
    "Gamer Impacto": {
        "text-type": "static",
        "input-text": "VICTORIA!",
        "font-family": "Lilita One",
        "font-size": "130",
        "font-weight": "800",
        "text-scale": "1.3",
        "color-type": "solid",
        "text-color": "#ffea00",
        "stroke-color": "#000000",
        "stroke-width": "6",
        "enable-shadow": "true",
        "shadow-color": "#000000",
        "shadow-blur": "0",
        "shadow-angle": "90",
        "shadow-distance": "12",
        "shadow-opacity": "80",
        "enable-neon": "false",
        "stagger-mode": "char",
        "stagger-speed": "0.04",
        "anim-preset": "elastic-bounce",
        "anim-duration": "1.8",
        "anim-delay": "0.1",
        "anim-ease": "back.out(1.7)",
        "loop-preset": "pulse",
        "loop-cycle-duration": "1.0",
        "loop-intensity": "1.2",
        "hold-duration": "3",
        "outro-preset": "slide-down",
        "outro-duration": "0.6",
        "outro-ease": "power2.in"
    },
    "Minimalista Elegante": {
        "text-type": "static",
        "input-text": "El Arte del Minimalismo",
        "font-family": "Playfair Display",
        "font-size": "70",
        "font-weight": "400",
        "text-scale": "1.0",
        "color-type": "solid",
        "text-color": "#ffffff",
        "stroke-color": "#000000",
        "stroke-width": "0",
        "enable-shadow": "true",
        "shadow-color": "#000000",
        "shadow-blur": "15",
        "shadow-angle": "45",
        "shadow-distance": "3",
        "shadow-opacity": "30",
        "enable-neon": "false",
        "stagger-mode": "word",
        "stagger-speed": "0.15",
        "anim-preset": "fade",
        "anim-duration": "2.0",
        "anim-delay": "0.5",
        "anim-ease": "power2.out",
        "loop-preset": "none",
        "hold-duration": "5",
        "outro-preset": "fade",
        "outro-duration": "1.2",
        "outro-ease": "none"
    }
};
